// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: clusters.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getClusterByName = `-- name: GetClusterByName :one
SELECT id, name, display_name, api_url, ca_bundle, oidc_issuer_url, default_namespace, created_at, updated_at FROM clusters WHERE name = $1
`

func (q *Queries) GetClusterByName(ctx context.Context, name string) (Cluster, error) {
	row := q.db.QueryRow(ctx, getClusterByName, name)
	var i Cluster
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DisplayName,
		&i.ApiUrl,
		&i.CaBundle,
		&i.OidcIssuerUrl,
		&i.DefaultNamespace,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertCluster = `-- name: InsertCluster :one
INSERT INTO clusters (name, display_name, api_url, ca_bundle, oidc_issuer_url, default_namespace)
VALUES ($1, $2, $3, $4, $5, $6) RETURNING id, name, display_name, api_url, ca_bundle, oidc_issuer_url, default_namespace, created_at, updated_at
`

type InsertClusterParams struct {
	Name             string      `json:"name"`
	DisplayName      pgtype.Text `json:"display_name"`
	ApiUrl           string      `json:"api_url"`
	CaBundle         pgtype.Text `json:"ca_bundle"`
	OidcIssuerUrl    string      `json:"oidc_issuer_url"`
	DefaultNamespace pgtype.Text `json:"default_namespace"`
}

func (q *Queries) InsertCluster(ctx context.Context, arg InsertClusterParams) (Cluster, error) {
	row := q.db.QueryRow(ctx, insertCluster,
		arg.Name,
		arg.DisplayName,
		arg.ApiUrl,
		arg.CaBundle,
		arg.OidcIssuerUrl,
		arg.DefaultNamespace,
	)
	var i Cluster
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DisplayName,
		&i.ApiUrl,
		&i.CaBundle,
		&i.OidcIssuerUrl,
		&i.DefaultNamespace,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listClusters = `-- name: ListClusters :many
SELECT id, name, display_name, api_url, ca_bundle, oidc_issuer_url, default_namespace, created_at, updated_at FROM clusters ORDER BY name
`

func (q *Queries) ListClusters(ctx context.Context) ([]Cluster, error) {
	rows, err := q.db.Query(ctx, listClusters)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Cluster
	for rows.Next() {
		var i Cluster
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.DisplayName,
			&i.ApiUrl,
			&i.CaBundle,
			&i.OidcIssuerUrl,
			&i.DefaultNamespace,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
