// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Cluster struct {
	ID               pgtype.UUID        `json:"id"`
	Name             string             `json:"name"`
	DisplayName      pgtype.Text        `json:"display_name"`
	ApiUrl           string             `json:"api_url"`
	CaBundle         pgtype.Text        `json:"ca_bundle"`
	OidcIssuerUrl    string             `json:"oidc_issuer_url"`
	DefaultNamespace pgtype.Text        `json:"default_namespace"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type Release struct {
	ID                pgtype.UUID        `json:"id"`
	Name              string             `json:"name"`
	TemplateVersionID pgtype.UUID        `json:"template_version_id"`
	ClusterID         pgtype.UUID        `json:"cluster_id"`
	Namespace         string             `json:"namespace"`
	ValuesJson        []byte             `json:"values_json"`
	RenderedYaml      string             `json:"rendered_yaml"`
	CreatedByUserID   pgtype.UUID        `json:"created_by_user_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type Session struct {
	ID                    pgtype.UUID        `json:"id"`
	UserID                pgtype.UUID        `json:"user_id"`
	IDTokenEncrypted      string             `json:"id_token_encrypted"`
	RefreshTokenEncrypted pgtype.Text        `json:"refresh_token_encrypted"`
	IDTokenExp            pgtype.Timestamptz `json:"id_token_exp"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	ExpiresAt             pgtype.Timestamptz `json:"expires_at"`
}

type Team struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	DisplayName pgtype.Text        `json:"display_name"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type TeamMembership struct {
	UserID    pgtype.UUID        `json:"user_id"`
	TeamID    pgtype.UUID        `json:"team_id"`
	Role      string             `json:"role"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Template struct {
	ID               pgtype.UUID        `json:"id"`
	Name             string             `json:"name"`
	DisplayName      string             `json:"display_name"`
	Description      pgtype.Text        `json:"description"`
	Tags             []string           `json:"tags"`
	OwnerUserID      pgtype.UUID        `json:"owner_user_id"`
	CurrentVersionID pgtype.UUID        `json:"current_version_id"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	OwningTeamID     pgtype.UUID        `json:"owning_team_id"`
}

type TemplateVersion struct {
	ID              pgtype.UUID        `json:"id"`
	TemplateID      pgtype.UUID        `json:"template_id"`
	Version         int32              `json:"version"`
	ResourcesYaml   string             `json:"resources_yaml"`
	UiSpecYaml      string             `json:"ui_spec_yaml"`
	MetadataYaml    pgtype.Text        `json:"metadata_yaml"`
	Status          string             `json:"status"`
	Notes           pgtype.Text        `json:"notes"`
	CreatedByUserID pgtype.UUID        `json:"created_by_user_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	PublishedAt     pgtype.Timestamptz `json:"published_at"`
	AuthoringMode   string             `json:"authoring_mode"`
	UiStateJson     []byte             `json:"ui_state_json"`
}

type User struct {
	ID          pgtype.UUID        `json:"id"`
	OidcSubject string             `json:"oidc_subject"`
	Email       pgtype.Text        `json:"email"`
	DisplayName pgtype.Text        `json:"display_name"`
	FirstSeenAt pgtype.Timestamptz `json:"first_seen_at"`
	LastSeenAt  pgtype.Timestamptz `json:"last_seen_at"`
}
