// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	DeleteSession(ctx context.Context, id pgtype.UUID) error
	GetSession(ctx context.Context, id pgtype.UUID) (Session, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	UpdateSessionTokens(ctx context.Context, arg UpdateSessionTokensParams) error
	UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
