// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: releases.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteRelease = `-- name: DeleteRelease :exec
DELETE FROM releases WHERE id = $1
`

func (q *Queries) DeleteRelease(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteRelease, id)
	return err
}

const getReleaseByID = `-- name: GetReleaseByID :one
SELECT r.id, r.name, r.template_version_id, r.cluster_id, r.namespace, r.values_json, r.rendered_yaml, r.created_by_user_id, r.created_at, r.updated_at, c.name AS cluster_name, c.api_url AS cluster_api_url, c.ca_bundle AS cluster_ca_bundle,
       t.name AS template_name, tv.version AS template_version, tv.ui_spec_yaml
  FROM releases r
  JOIN clusters c          ON c.id = r.cluster_id
  JOIN template_versions tv ON tv.id = r.template_version_id
  JOIN templates t         ON t.id = tv.template_id
 WHERE r.id = $1
`

type GetReleaseByIDRow struct {
	ID                pgtype.UUID        `json:"id"`
	Name              string             `json:"name"`
	TemplateVersionID pgtype.UUID        `json:"template_version_id"`
	ClusterID         pgtype.UUID        `json:"cluster_id"`
	Namespace         string             `json:"namespace"`
	ValuesJson        []byte             `json:"values_json"`
	RenderedYaml      string             `json:"rendered_yaml"`
	CreatedByUserID   pgtype.UUID        `json:"created_by_user_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	ClusterName       string             `json:"cluster_name"`
	ClusterApiUrl     string             `json:"cluster_api_url"`
	ClusterCaBundle   pgtype.Text        `json:"cluster_ca_bundle"`
	TemplateName      string             `json:"template_name"`
	TemplateVersion   int32              `json:"template_version"`
	UiSpecYaml        string             `json:"ui_spec_yaml"`
}

func (q *Queries) GetReleaseByID(ctx context.Context, id pgtype.UUID) (GetReleaseByIDRow, error) {
	row := q.db.QueryRow(ctx, getReleaseByID, id)
	var i GetReleaseByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TemplateVersionID,
		&i.ClusterID,
		&i.Namespace,
		&i.ValuesJson,
		&i.RenderedYaml,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClusterName,
		&i.ClusterApiUrl,
		&i.ClusterCaBundle,
		&i.TemplateName,
		&i.TemplateVersion,
		&i.UiSpecYaml,
	)
	return i, err
}

const insertRelease = `-- name: InsertRelease :one
INSERT INTO releases (name, template_version_id, cluster_id, namespace, values_json, rendered_yaml, created_by_user_id)
VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING id, name, template_version_id, cluster_id, namespace, values_json, rendered_yaml, created_by_user_id, created_at, updated_at
`

type InsertReleaseParams struct {
	Name              string      `json:"name"`
	TemplateVersionID pgtype.UUID `json:"template_version_id"`
	ClusterID         pgtype.UUID `json:"cluster_id"`
	Namespace         string      `json:"namespace"`
	ValuesJson        []byte      `json:"values_json"`
	RenderedYaml      string      `json:"rendered_yaml"`
	CreatedByUserID   pgtype.UUID `json:"created_by_user_id"`
}

func (q *Queries) InsertRelease(ctx context.Context, arg InsertReleaseParams) (Release, error) {
	row := q.db.QueryRow(ctx, insertRelease,
		arg.Name,
		arg.TemplateVersionID,
		arg.ClusterID,
		arg.Namespace,
		arg.ValuesJson,
		arg.RenderedYaml,
		arg.CreatedByUserID,
	)
	var i Release
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TemplateVersionID,
		&i.ClusterID,
		&i.Namespace,
		&i.ValuesJson,
		&i.RenderedYaml,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllReleases = `-- name: ListAllReleases :many
SELECT r.id, r.name, r.template_version_id, r.cluster_id, r.namespace, r.values_json, r.rendered_yaml, r.created_by_user_id, r.created_at, r.updated_at, c.name AS cluster_name, t.name AS template_name, tv.version AS template_version
  FROM releases r
  JOIN clusters c          ON c.id = r.cluster_id
  JOIN template_versions tv ON tv.id = r.template_version_id
  JOIN templates t         ON t.id = tv.template_id
 ORDER BY r.created_at DESC
`

type ListAllReleasesRow struct {
	ID                pgtype.UUID        `json:"id"`
	Name              string             `json:"name"`
	TemplateVersionID pgtype.UUID        `json:"template_version_id"`
	ClusterID         pgtype.UUID        `json:"cluster_id"`
	Namespace         string             `json:"namespace"`
	ValuesJson        []byte             `json:"values_json"`
	RenderedYaml      string             `json:"rendered_yaml"`
	CreatedByUserID   pgtype.UUID        `json:"created_by_user_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	ClusterName       string             `json:"cluster_name"`
	TemplateName      string             `json:"template_name"`
	TemplateVersion   int32              `json:"template_version"`
}

func (q *Queries) ListAllReleases(ctx context.Context) ([]ListAllReleasesRow, error) {
	rows, err := q.db.Query(ctx, listAllReleases)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllReleasesRow
	for rows.Next() {
		var i ListAllReleasesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TemplateVersionID,
			&i.ClusterID,
			&i.Namespace,
			&i.ValuesJson,
			&i.RenderedYaml,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ClusterName,
			&i.TemplateName,
			&i.TemplateVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReleasesForUser = `-- name: ListReleasesForUser :many
SELECT r.id, r.name, r.template_version_id, r.cluster_id, r.namespace, r.values_json, r.rendered_yaml, r.created_by_user_id, r.created_at, r.updated_at, c.name AS cluster_name, t.name AS template_name, tv.version AS template_version
  FROM releases r
  JOIN clusters c          ON c.id = r.cluster_id
  JOIN template_versions tv ON tv.id = r.template_version_id
  JOIN templates t         ON t.id = tv.template_id
 WHERE r.created_by_user_id = $1
 ORDER BY r.created_at DESC
`

type ListReleasesForUserRow struct {
	ID                pgtype.UUID        `json:"id"`
	Name              string             `json:"name"`
	TemplateVersionID pgtype.UUID        `json:"template_version_id"`
	ClusterID         pgtype.UUID        `json:"cluster_id"`
	Namespace         string             `json:"namespace"`
	ValuesJson        []byte             `json:"values_json"`
	RenderedYaml      string             `json:"rendered_yaml"`
	CreatedByUserID   pgtype.UUID        `json:"created_by_user_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	ClusterName       string             `json:"cluster_name"`
	TemplateName      string             `json:"template_name"`
	TemplateVersion   int32              `json:"template_version"`
}

func (q *Queries) ListReleasesForUser(ctx context.Context, createdByUserID pgtype.UUID) ([]ListReleasesForUserRow, error) {
	rows, err := q.db.Query(ctx, listReleasesForUser, createdByUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReleasesForUserRow
	for rows.Next() {
		var i ListReleasesForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TemplateVersionID,
			&i.ClusterID,
			&i.Namespace,
			&i.ValuesJson,
			&i.RenderedYaml,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ClusterName,
			&i.TemplateName,
			&i.TemplateVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
