// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (user_id, id_token_encrypted, refresh_token_encrypted, id_token_exp, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, id_token_encrypted, refresh_token_encrypted, id_token_exp, created_at, expires_at
`

type CreateSessionParams struct {
	UserID                pgtype.UUID        `json:"user_id"`
	IDTokenEncrypted      string             `json:"id_token_encrypted"`
	RefreshTokenEncrypted pgtype.Text        `json:"refresh_token_encrypted"`
	IDTokenExp            pgtype.Timestamptz `json:"id_token_exp"`
	ExpiresAt             pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.UserID,
		arg.IDTokenEncrypted,
		arg.RefreshTokenEncrypted,
		arg.IDTokenExp,
		arg.ExpiresAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.IDTokenEncrypted,
		&i.RefreshTokenEncrypted,
		&i.IDTokenExp,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE id = $1
`

func (q *Queries) DeleteSession(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteSession, id)
	return err
}

const getSession = `-- name: GetSession :one
SELECT id, user_id, id_token_encrypted, refresh_token_encrypted, id_token_exp, created_at, expires_at FROM sessions WHERE id = $1 AND expires_at > now()
`

func (q *Queries) GetSession(ctx context.Context, id pgtype.UUID) (Session, error) {
	row := q.db.QueryRow(ctx, getSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.IDTokenEncrypted,
		&i.RefreshTokenEncrypted,
		&i.IDTokenExp,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const updateSessionTokens = `-- name: UpdateSessionTokens :exec
UPDATE sessions
   SET id_token_encrypted = $2, refresh_token_encrypted = $3, id_token_exp = $4
 WHERE id = $1
`

type UpdateSessionTokensParams struct {
	ID                    pgtype.UUID        `json:"id"`
	IDTokenEncrypted      string             `json:"id_token_encrypted"`
	RefreshTokenEncrypted pgtype.Text        `json:"refresh_token_encrypted"`
	IDTokenExp            pgtype.Timestamptz `json:"id_token_exp"`
}

func (q *Queries) UpdateSessionTokens(ctx context.Context, arg UpdateSessionTokensParams) error {
	_, err := q.db.Exec(ctx, updateSessionTokens,
		arg.ID,
		arg.IDTokenEncrypted,
		arg.RefreshTokenEncrypted,
		arg.IDTokenExp,
	)
	return err
}
