// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: teams.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countTemplatesForTeam = `-- name: CountTemplatesForTeam :one
SELECT COUNT(*) FROM templates WHERE owning_team_id = $1
`

func (q *Queries) CountTemplatesForTeam(ctx context.Context, owningTeamID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countTemplatesForTeam, owningTeamID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteTeam = `-- name: DeleteTeam :exec
DELETE FROM teams WHERE id = $1
`

func (q *Queries) DeleteTeam(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteTeam, id)
	return err
}

const deleteTeamMembership = `-- name: DeleteTeamMembership :exec
DELETE FROM team_memberships WHERE team_id = $1 AND user_id = $2
`

type DeleteTeamMembershipParams struct {
	TeamID pgtype.UUID `json:"team_id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteTeamMembership(ctx context.Context, arg DeleteTeamMembershipParams) error {
	_, err := q.db.Exec(ctx, deleteTeamMembership, arg.TeamID, arg.UserID)
	return err
}

const getTeamByID = `-- name: GetTeamByID :one
SELECT id, name, display_name, created_at FROM teams WHERE id = $1
`

func (q *Queries) GetTeamByID(ctx context.Context, id pgtype.UUID) (Team, error) {
	row := q.db.QueryRow(ctx, getTeamByID, id)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DisplayName,
		&i.CreatedAt,
	)
	return i, err
}

const getTeamByName = `-- name: GetTeamByName :one
SELECT id, name, display_name, created_at FROM teams WHERE name = $1
`

func (q *Queries) GetTeamByName(ctx context.Context, name string) (Team, error) {
	row := q.db.QueryRow(ctx, getTeamByName, name)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DisplayName,
		&i.CreatedAt,
	)
	return i, err
}

const getTeamMembership = `-- name: GetTeamMembership :one
SELECT user_id, team_id, role, created_at FROM team_memberships WHERE team_id = $1 AND user_id = $2
`

type GetTeamMembershipParams struct {
	TeamID pgtype.UUID `json:"team_id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetTeamMembership(ctx context.Context, arg GetTeamMembershipParams) (TeamMembership, error) {
	row := q.db.QueryRow(ctx, getTeamMembership, arg.TeamID, arg.UserID)
	var i TeamMembership
	err := row.Scan(
		&i.UserID,
		&i.TeamID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const insertTeam = `-- name: InsertTeam :one
INSERT INTO teams (name, display_name)
VALUES ($1, $2)
RETURNING id, name, display_name, created_at
`

type InsertTeamParams struct {
	Name        string      `json:"name"`
	DisplayName pgtype.Text `json:"display_name"`
}

func (q *Queries) InsertTeam(ctx context.Context, arg InsertTeamParams) (Team, error) {
	row := q.db.QueryRow(ctx, insertTeam, arg.Name, arg.DisplayName)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DisplayName,
		&i.CreatedAt,
	)
	return i, err
}

const insertTeamMembership = `-- name: InsertTeamMembership :one
INSERT INTO team_memberships (user_id, team_id, role)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, team_id) DO UPDATE SET role = EXCLUDED.role
RETURNING user_id, team_id, role, created_at
`

type InsertTeamMembershipParams struct {
	UserID pgtype.UUID `json:"user_id"`
	TeamID pgtype.UUID `json:"team_id"`
	Role   string      `json:"role"`
}

func (q *Queries) InsertTeamMembership(ctx context.Context, arg InsertTeamMembershipParams) (TeamMembership, error) {
	row := q.db.QueryRow(ctx, insertTeamMembership, arg.UserID, arg.TeamID, arg.Role)
	var i TeamMembership
	err := row.Scan(
		&i.UserID,
		&i.TeamID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const listTeamMembers = `-- name: ListTeamMembers :many
SELECT tm.user_id, tm.team_id, tm.role, tm.created_at, u.email, u.display_name AS user_display_name
  FROM team_memberships tm
  JOIN users u ON u.id = tm.user_id
 WHERE tm.team_id = $1
 ORDER BY u.email
`

type ListTeamMembersRow struct {
	UserID          pgtype.UUID        `json:"user_id"`
	TeamID          pgtype.UUID        `json:"team_id"`
	Role            string             `json:"role"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	Email           pgtype.Text        `json:"email"`
	UserDisplayName pgtype.Text        `json:"user_display_name"`
}

func (q *Queries) ListTeamMembers(ctx context.Context, teamID pgtype.UUID) ([]ListTeamMembersRow, error) {
	rows, err := q.db.Query(ctx, listTeamMembers, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTeamMembersRow
	for rows.Next() {
		var i ListTeamMembersRow
		if err := rows.Scan(
			&i.UserID,
			&i.TeamID,
			&i.Role,
			&i.CreatedAt,
			&i.Email,
			&i.UserDisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeams = `-- name: ListTeams :many
SELECT id, name, display_name, created_at FROM teams ORDER BY name
`

func (q *Queries) ListTeams(ctx context.Context) ([]Team, error) {
	rows, err := q.db.Query(ctx, listTeams)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Team
	for rows.Next() {
		var i Team
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.DisplayName,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamsForUser = `-- name: ListTeamsForUser :many
SELECT t.id, t.name, t.display_name, t.created_at FROM teams t
  JOIN team_memberships m ON m.team_id = t.id
 WHERE m.user_id = $1
 ORDER BY t.name
`

func (q *Queries) ListTeamsForUser(ctx context.Context, userID pgtype.UUID) ([]Team, error) {
	rows, err := q.db.Query(ctx, listTeamsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Team
	for rows.Next() {
		var i Team
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.DisplayName,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
