// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: templates.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getTemplateByName = `-- name: GetTemplateByName :one
SELECT id, name, display_name, description, tags, owner_user_id, current_version_id, created_at, updated_at FROM templates WHERE name = $1
`

func (q *Queries) GetTemplateByName(ctx context.Context, name string) (Template, error) {
	row := q.db.QueryRow(ctx, getTemplateByName, name)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DisplayName,
		&i.Description,
		&i.Tags,
		&i.OwnerUserID,
		&i.CurrentVersionID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTemplateVersion = `-- name: GetTemplateVersion :one
SELECT tv.id, tv.template_id, tv.version, tv.resources_yaml, tv.ui_spec_yaml, tv.metadata_yaml, tv.status, tv.notes, tv.created_by_user_id, tv.created_at, tv.published_at FROM template_versions tv
  JOIN templates t ON t.id = tv.template_id
 WHERE t.name = $1 AND tv.version = $2
`

type GetTemplateVersionParams struct {
	Name    string `json:"name"`
	Version int32  `json:"version"`
}

func (q *Queries) GetTemplateVersion(ctx context.Context, arg GetTemplateVersionParams) (TemplateVersion, error) {
	row := q.db.QueryRow(ctx, getTemplateVersion, arg.Name, arg.Version)
	var i TemplateVersion
	err := row.Scan(
		&i.ID,
		&i.TemplateID,
		&i.Version,
		&i.ResourcesYaml,
		&i.UiSpecYaml,
		&i.MetadataYaml,
		&i.Status,
		&i.Notes,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.PublishedAt,
	)
	return i, err
}

const insertTemplate = `-- name: InsertTemplate :one
INSERT INTO templates (name, display_name, description, tags, owner_user_id)
VALUES ($1, $2, $3, $4, $5) RETURNING id, name, display_name, description, tags, owner_user_id, current_version_id, created_at, updated_at
`

type InsertTemplateParams struct {
	Name        string      `json:"name"`
	DisplayName string      `json:"display_name"`
	Description pgtype.Text `json:"description"`
	Tags        []string    `json:"tags"`
	OwnerUserID pgtype.UUID `json:"owner_user_id"`
}

func (q *Queries) InsertTemplate(ctx context.Context, arg InsertTemplateParams) (Template, error) {
	row := q.db.QueryRow(ctx, insertTemplate,
		arg.Name,
		arg.DisplayName,
		arg.Description,
		arg.Tags,
		arg.OwnerUserID,
	)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DisplayName,
		&i.Description,
		&i.Tags,
		&i.OwnerUserID,
		&i.CurrentVersionID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertTemplateVersion = `-- name: InsertTemplateVersion :one
INSERT INTO template_versions (
  template_id, version, resources_yaml, ui_spec_yaml, metadata_yaml, status, notes, created_by_user_id
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8) RETURNING id, template_id, version, resources_yaml, ui_spec_yaml, metadata_yaml, status, notes, created_by_user_id, created_at, published_at
`

type InsertTemplateVersionParams struct {
	TemplateID      pgtype.UUID `json:"template_id"`
	Version         int32       `json:"version"`
	ResourcesYaml   string      `json:"resources_yaml"`
	UiSpecYaml      string      `json:"ui_spec_yaml"`
	MetadataYaml    pgtype.Text `json:"metadata_yaml"`
	Status          string      `json:"status"`
	Notes           pgtype.Text `json:"notes"`
	CreatedByUserID pgtype.UUID `json:"created_by_user_id"`
}

func (q *Queries) InsertTemplateVersion(ctx context.Context, arg InsertTemplateVersionParams) (TemplateVersion, error) {
	row := q.db.QueryRow(ctx, insertTemplateVersion,
		arg.TemplateID,
		arg.Version,
		arg.ResourcesYaml,
		arg.UiSpecYaml,
		arg.MetadataYaml,
		arg.Status,
		arg.Notes,
		arg.CreatedByUserID,
	)
	var i TemplateVersion
	err := row.Scan(
		&i.ID,
		&i.TemplateID,
		&i.Version,
		&i.ResourcesYaml,
		&i.UiSpecYaml,
		&i.MetadataYaml,
		&i.Status,
		&i.Notes,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.PublishedAt,
	)
	return i, err
}

const listTemplateVersions = `-- name: ListTemplateVersions :many
SELECT tv.id, tv.template_id, tv.version, tv.resources_yaml, tv.ui_spec_yaml, tv.metadata_yaml, tv.status, tv.notes, tv.created_by_user_id, tv.created_at, tv.published_at FROM template_versions tv
  JOIN templates t ON t.id = tv.template_id
 WHERE t.name = $1
 ORDER BY tv.version DESC
`

func (q *Queries) ListTemplateVersions(ctx context.Context, name string) ([]TemplateVersion, error) {
	rows, err := q.db.Query(ctx, listTemplateVersions, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TemplateVersion
	for rows.Next() {
		var i TemplateVersion
		if err := rows.Scan(
			&i.ID,
			&i.TemplateID,
			&i.Version,
			&i.ResourcesYaml,
			&i.UiSpecYaml,
			&i.MetadataYaml,
			&i.Status,
			&i.Notes,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTemplates = `-- name: ListTemplates :many
SELECT t.id, t.name, t.display_name, t.description, t.tags, t.owner_user_id, t.current_version_id, t.created_at, t.updated_at,
       tv.version    AS current_version,
       tv.ui_spec_yaml AS current_ui_spec
  FROM templates t
  LEFT JOIN template_versions tv ON tv.id = t.current_version_id
 ORDER BY t.name
`

type ListTemplatesRow struct {
	ID               pgtype.UUID        `json:"id"`
	Name             string             `json:"name"`
	DisplayName      string             `json:"display_name"`
	Description      pgtype.Text        `json:"description"`
	Tags             []string           `json:"tags"`
	OwnerUserID      pgtype.UUID        `json:"owner_user_id"`
	CurrentVersionID pgtype.UUID        `json:"current_version_id"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	CurrentVersion   pgtype.Int4        `json:"current_version"`
	CurrentUiSpec    pgtype.Text        `json:"current_ui_spec"`
}

func (q *Queries) ListTemplates(ctx context.Context) ([]ListTemplatesRow, error) {
	rows, err := q.db.Query(ctx, listTemplates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTemplatesRow
	for rows.Next() {
		var i ListTemplatesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.DisplayName,
			&i.Description,
			&i.Tags,
			&i.OwnerUserID,
			&i.CurrentVersionID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CurrentVersion,
			&i.CurrentUiSpec,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextTemplateVersion = `-- name: NextTemplateVersion :one
SELECT COALESCE(MAX(version), 0) + 1 FROM template_versions WHERE template_id = $1
`

func (q *Queries) NextTemplateVersion(ctx context.Context, templateID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, nextTemplateVersion, templateID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const publishTemplateVersion = `-- name: PublishTemplateVersion :one
UPDATE template_versions
   SET status = 'published', published_at = now()
 WHERE id = $1 AND status = 'draft'
 RETURNING id, template_id, version, resources_yaml, ui_spec_yaml, metadata_yaml, status, notes, created_by_user_id, created_at, published_at
`

func (q *Queries) PublishTemplateVersion(ctx context.Context, id pgtype.UUID) (TemplateVersion, error) {
	row := q.db.QueryRow(ctx, publishTemplateVersion, id)
	var i TemplateVersion
	err := row.Scan(
		&i.ID,
		&i.TemplateID,
		&i.Version,
		&i.ResourcesYaml,
		&i.UiSpecYaml,
		&i.MetadataYaml,
		&i.Status,
		&i.Notes,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.PublishedAt,
	)
	return i, err
}

const updateTemplateCurrentVersion = `-- name: UpdateTemplateCurrentVersion :exec
UPDATE templates SET current_version_id = $2, updated_at = now() WHERE id = $1
`

type UpdateTemplateCurrentVersionParams struct {
	ID               pgtype.UUID `json:"id"`
	CurrentVersionID pgtype.UUID `json:"current_version_id"`
}

func (q *Queries) UpdateTemplateCurrentVersion(ctx context.Context, arg UpdateTemplateCurrentVersionParams) error {
	_, err := q.db.Exec(ctx, updateTemplateCurrentVersion, arg.ID, arg.CurrentVersionID)
	return err
}
