// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, oidc_subject, email, display_name, first_seen_at, last_seen_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.OidcSubject,
		&i.Email,
		&i.DisplayName,
		&i.FirstSeenAt,
		&i.LastSeenAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, oidc_subject, email, display_name, first_seen_at, last_seen_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.OidcSubject,
		&i.Email,
		&i.DisplayName,
		&i.FirstSeenAt,
		&i.LastSeenAt,
	)
	return i, err
}

const upsertUser = `-- name: UpsertUser :one
INSERT INTO users (oidc_subject, email, display_name, first_seen_at, last_seen_at)
VALUES ($1, $2, $3, now(), now())
ON CONFLICT (oidc_subject) DO UPDATE
   SET email = EXCLUDED.email,
       display_name = EXCLUDED.display_name,
       last_seen_at = now()
RETURNING id, oidc_subject, email, display_name, first_seen_at, last_seen_at
`

type UpsertUserParams struct {
	OidcSubject string      `json:"oidc_subject"`
	Email       pgtype.Text `json:"email"`
	DisplayName pgtype.Text `json:"display_name"`
}

func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertUser, arg.OidcSubject, arg.Email, arg.DisplayName)
	var i User
	err := row.Scan(
		&i.ID,
		&i.OidcSubject,
		&i.Email,
		&i.DisplayName,
		&i.FirstSeenAt,
		&i.LastSeenAt,
	)
	return i, err
}
