apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kuberport.backend.fullname" . }}
  labels:
    {{- include "kuberport.backend.labels" . | nindent 4 }}
data:
  LISTEN_ADDR: {{ printf ":%v" .Values.backend.service.port | quote }}
  OIDC_ISSUER: {{ required "oidc.issuer is required" .Values.oidc.issuer | quote }}
  OIDC_AUDIENCE: {{ required "oidc.audience is required" .Values.oidc.audience | quote }}
  KBP_OPENAPI_CACHE_MAX: {{ .Values.backend.openapiCacheMax | quote }}
