apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kuberport.frontend.fullname" . }}
  labels:
    {{- include "kuberport.frontend.labels" . | nindent 4 }}
data:
  OIDC_ISSUER: {{ required "oidc.issuer is required" .Values.oidc.issuer | quote }}
  OIDC_CLIENT_ID: {{ required "oidc.clientId is required" .Values.oidc.clientId | quote }}
  OIDC_REDIRECT_URI: {{ include "kuberport.oidc.redirectUri" . | quote }}
  GO_API_BASE_URL: {{ printf "http://%s:%v" (include "kuberport.backend.fullname" .) .Values.backend.service.port | quote }}
